import ast
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"

EXPECTED_SKILLS = {
    "llvm-api-grounding",
    "git-conflict-context",
    "update-test-checks",
    "alive2-verify",
    "lit-failure-triage",
    "downstream-patch-ledger",
    "tablegen-expand",
    "patch-progress-dashboard",
    "cherry-pick-runner",
    "metaxgpu-cherry-pick-operator",
    "agent-memory",
}


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    assert text.startswith("---\n")
    end = text.index("\n---", 4)
    data = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"')
    return data


class SkillPackTest(unittest.TestCase):
    def test_expected_skills_exist_with_valid_frontmatter(self):
        self.assertTrue(SKILLS.is_dir())
        names = {p.name for p in SKILLS.iterdir() if p.is_dir()}
        self.assertLessEqual(EXPECTED_SKILLS, names)

        for name in EXPECTED_SKILLS:
            skill = SKILLS / name / "SKILL.md"
            self.assertTrue(skill.is_file(), str(skill))
            meta = frontmatter(skill)
            self.assertEqual(meta["name"], name)
            self.assertTrue(meta["description"].startswith("Use when"))
            self.assertLess(len(meta["description"]), 700)

    def test_every_skill_has_at_least_one_python_script_that_compiles(self):
        for name in EXPECTED_SKILLS:
            scripts = sorted((SKILLS / name / "scripts").glob("*.py"))
            self.assertTrue(scripts, f"{name} has no helper scripts")
            for script in scripts:
                ast.parse(script.read_text(encoding="utf-8"), filename=str(script))

    def test_skills_do_not_contain_template_placeholders(self):
        for name in EXPECTED_SKILLS:
            for path in [SKILLS / name / "SKILL.md", SKILLS / name / "agents" / "openai.yaml"]:
                self.assertTrue(path.is_file(), str(path))
                text = path.read_text(encoding="utf-8")
                self.assertNotIn("TODO", text)
                self.assertNotIn("[TODO", text)

    def test_board_and_agent_entrypoints_exist(self):
        self.assertTrue((ROOT / "BOARD.md").is_file())
        self.assertTrue((ROOT / "AGENTS.md").is_file())
        self.assertTrue((ROOT / "docs" / "mvp-skill-pack.md").is_file())

    def test_ledger_accepts_ledger_argument_after_subcommand(self):
        script = SKILLS / "downstream-patch-ledger" / "scripts" / "ledger.py"
        with tempfile.TemporaryDirectory() as tmp:
            ledger = Path(tmp) / "patches.jsonl"
            proc = subprocess.run(
                [sys.executable, str(script), "init", "--ledger", str(ledger)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(proc.returncode, 0, proc.stderr)
            self.assertTrue(ledger.is_file())

    def test_api_grounding_records_memory_when_enabled(self):
        script = SKILLS / "llvm-api-grounding" / "scripts" / "ground_api.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            repo = root / "repo"
            header = repo / "llvm" / "include" / "llvm" / "IR" / "Instruction.h"
            header.parent.mkdir(parents=True)
            header.write_text("class Instruction { void moveBefore(); };\n", encoding="utf-8")
            memory = root / "memories"

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "moveBefore",
                    "--repo",
                    str(repo),
                    "--memory-dir",
                    str(memory),
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            rows = [
                json.loads(line)
                for line in (memory / "trusted.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertEqual(rows[0]["kind"], "llvm-api-grounding")
            self.assertIn("moveBefore", rows[0]["summary"])
            self.assertEqual(rows[0]["confidence"], "trusted")

    def test_lit_triage_records_candidate_memory_when_enabled(self):
        script = SKILLS / "lit-failure-triage" / "scripts" / "triage_lit_failure.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            test = root / "foo.ll"
            log = root / "lit.log"
            memory = root / "memories"
            test.write_text(
                "; NOTE: Assertions have been autogenerated by utils/update_test_checks.py\n; RUN: opt < %s | FileCheck %s\n",
                encoding="utf-8",
            )
            log.write_text("FileCheck error: CHECK: expected string not found\n", encoding="utf-8")

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    str(test),
                    "--from-log",
                    str(log),
                    "--memory-dir",
                    str(memory),
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 1)
            rows = [
                json.loads(line)
                for line in (memory / "candidates.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertEqual(rows[0]["kind"], "lit-failure-triage")
            self.assertIn("PURE_TEXT_DRIFT", rows[0]["applies_to"])

    def test_lit_triage_prefers_downstream_break_for_metax_failures(self):
        script = SKILLS / "lit-failure-triage" / "scripts" / "triage_lit_failure.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            test = root / "metax.ll"
            log = root / "lit.log"
            test.write_text(
                "; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py\n; RUN: llc -mtriple=metax < %s | FileCheck %s\n",
                encoding="utf-8",
            )
            log.write_text("FileCheck error: CHECK: expected string not found\n", encoding="utf-8")

            proc = subprocess.run(
                [sys.executable, str(script), str(test), "--from-log", str(log)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 1)
            self.assertIn("classification: DOWNSTREAM_BREAK", proc.stdout)

    def test_alive2_verify_records_memory_when_enabled(self):
        script = SKILLS / "alive2-verify" / "scripts" / "alive2_verify.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            alive = root / "alive-tv"
            ir = root / "test.ll"
            memory = root / "memories"
            alive.write_text("#!/bin/sh\necho '0 incorrect transformations'\nexit 0\n", encoding="utf-8")
            alive.chmod(0o755)
            ir.write_text("define i32 @f() { ret i32 0 }\n", encoding="utf-8")

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    str(ir),
                    "--alive-tv",
                    str(alive),
                    "--memory-dir",
                    str(memory),
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            rows = [
                json.loads(line)
                for line in (memory / "trusted.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertEqual(rows[0]["kind"], "alive2-result")
            self.assertIn("ALIVE2_PASS", rows[0]["applies_to"])

    def test_dashboard_renders_progress_outputs(self):
        script = SKILLS / "patch-progress-dashboard" / "scripts" / "render_dashboard.py"
        with tempfile.TemporaryDirectory() as tmp:
            progress = Path(tmp) / "progress"
            (progress / "agents").mkdir(parents=True)
            (progress / "packets").mkdir()
            (progress / "events.jsonl").write_text(
                "\n".join(
                    [
                        '{"ts":"2026-05-07T12:00:00+08:00","agent":"agent-001","sha":"aaa111","seq":1,"state":"CLAIMED","files":["llvm/lib/Target/MetaxGPU/A.cpp"],"message":"claimed"}',
                        '{"ts":"2026-05-07T12:01:00+08:00","agent":"agent-001","sha":"aaa111","seq":1,"state":"CLEAN","files":["llvm/lib/Target/MetaxGPU/A.cpp"],"message":"clean cherry-pick"}',
                        '{"ts":"2026-05-07T12:02:00+08:00","agent":"agent-002","sha":"bbb222","seq":2,"state":"NEED_HUMAN","files":["llvm/lib/CodeGen/B.cpp"],"message":"semantic conflict"}',
                    ]
                )
                + "\n",
                encoding="utf-8",
            )
            (progress / "agents" / "agent-001.json").write_text(
                '{"agent":"agent-001","status":"idle","current_sha":"aaa111","current_seq":1,"state":"CLEAN","updated_at":"2026-05-07T12:01:00+08:00"}',
                encoding="utf-8",
            )
            (progress / "agents" / "agent-002.json").write_text(
                '{"agent":"agent-002","status":"waiting","current_sha":"bbb222","current_seq":2,"state":"NEED_HUMAN","updated_at":"2026-05-07T12:02:00+08:00"}',
                encoding="utf-8",
            )

            proc = subprocess.run(
                [sys.executable, str(script), str(progress)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            dashboard = (progress / "DASHBOARD.md").read_text(encoding="utf-8")
            html = (progress / "dashboard.html").read_text(encoding="utf-8")
            summary = json.loads((progress / "api" / "summary.json").read_text(encoding="utf-8"))
            self.assertIn("Total patches: 2", dashboard)
            self.assertIn("Need human: 1", dashboard)
            self.assertIn("bbb222", html)
            self.assertEqual(summary["total"], 2)
            self.assertEqual(summary["states"]["CLEAN"], 1)
            self.assertEqual(summary["states"]["NEED_HUMAN"], 1)

    def test_dashboard_html_limits_bulk_patch_rows(self):
        script = SKILLS / "patch-progress-dashboard" / "scripts" / "render_dashboard.py"
        with tempfile.TemporaryDirectory() as tmp:
            progress = Path(tmp) / "progress"
            progress.mkdir()
            events = []
            for seq in range(1, 251):
                sha = f"done{seq:03d}"
                events.append(
                    json.dumps(
                        {
                            "ts": f"2026-05-07T12:{seq % 60:02d}:00+08:00",
                            "agent": "agent-001",
                            "sha": sha,
                            "seq": seq,
                            "state": "DONE",
                            "files": [f"llvm/lib/Target/MetaxGPU/File{seq}.cpp"],
                            "message": f"done patch {seq}",
                        },
                        sort_keys=True,
                    )
                )
            events.append(
                json.dumps(
                    {
                        "ts": "2026-05-07T13:00:00+08:00",
                        "agent": "agent-001",
                        "sha": "needhuman999",
                        "seq": 251,
                        "state": "NEED_HUMAN",
                        "files": ["llvm/lib/TargetParser/Triple.cpp"],
                        "message": "semantic conflict",
                    },
                    sort_keys=True,
                )
            )
            (progress / "events.jsonl").write_text("\n".join(events) + "\n", encoding="utf-8")

            proc = subprocess.run(
                [sys.executable, str(script), str(progress)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            html = (progress / "dashboard.html").read_text(encoding="utf-8")
            patches = json.loads((progress / "api" / "patches.json").read_text(encoding="utf-8"))
            self.assertIn("api/patches.json", html)
            self.assertIn("needhuman999", html)
            self.assertIn("done250", html)
            self.assertNotIn("done001", html)
            self.assertLess(len(html), 90000)
            self.assertEqual(len(patches), 251)
            self.assertEqual(patches[0]["sha"], "done001")

    def test_cherry_pick_runner_writes_default_hybrid_config(self):
        script = SKILLS / "cherry-pick-runner" / "scripts" / "cherry_pick_runner.py"
        with tempfile.TemporaryDirectory() as tmp:
            config = Path(tmp) / "runner-config.json"
            proc = subprocess.run(
                [sys.executable, str(script), "init-config", "--output", str(config)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            data = json.loads(config.read_text(encoding="utf-8"))
            self.assertEqual(data["worker_count"], 1)
            self.assertEqual(data["gate_strategy"], "hybrid")
            self.assertGreater(data["full_gate_interval"], 0)
            self.assertTrue(data["auto_amend_after_repair"])
            self.assertEqual(data["build_repair"]["max_attempts"], 3)
            self.assertEqual(data["test_repair"]["max_attempts"], 2)

    def test_cherry_pick_runner_dry_run_records_hybrid_gate_events(self):
        script = SKILLS / "cherry-pick-runner" / "scripts" / "cherry_pick_runner.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            manifest = root / "patches.jsonl"
            config = root / "runner-config.json"
            progress = root / "progress"
            manifest.write_text(
                "\n".join(
                    [
                        '{"seq":1,"sha":"aaa111","title":"normal patch","risk":"low","files":["llvm/lib/Target/MetaxGPU/A.cpp"]}',
                        '{"seq":2,"sha":"bbb222","title":"tablegen patch","risk":"low","files":["llvm/lib/Target/MetaxGPU/B.td"]}',
                        '{"seq":3,"sha":"ccc333","title":"third patch","risk":"low","files":["llvm/lib/Target/MetaxGPU/C.cpp"]}',
                    ]
                )
                + "\n",
                encoding="utf-8",
            )
            config.write_text(
                json.dumps(
                    {
                        "worker_count": 1,
                        "gate_strategy": "hybrid",
                        "full_gate_interval": 3,
                        "quick_build_commands": [],
                        "quick_test_commands": [],
                        "full_build_commands": [],
                        "full_test_commands": [],
                        "high_risk_patterns": [".td"],
                        "build_repair": {"max_attempts": 3, "command": []},
                        "test_repair": {"max_attempts": 2, "command": []},
                    }
                )
                + "\n",
                encoding="utf-8",
            )

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "run",
                    "--manifest",
                    str(manifest),
                    "--config",
                    str(config),
                    "--progress",
                    str(progress),
                    "--dry-run",
                    "--limit",
                    "3",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            events = [
                json.loads(line)
                for line in (progress / "events.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            gates = {
                event["sha"]: event["gate"]
                for event in events
                if event.get("state") == "GATE_SELECTED"
            }
            self.assertEqual(gates["aaa111"], "quick")
            self.assertEqual(gates["bbb222"], "heavy")
            self.assertEqual(gates["ccc333"], "full")

    def test_cherry_pick_runner_accepts_bom_encoded_manifest(self):
        script = SKILLS / "cherry-pick-runner" / "scripts" / "cherry_pick_runner.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            manifest = root / "patches.jsonl"
            progress = root / "progress"
            manifest.write_text(
                '{"seq":1,"sha":"aaa111","title":"bom patch","risk":"low","files":["llvm/lib/Target/MetaxGPU/A.cpp"]}\n',
                encoding="utf-8-sig",
            )

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "run",
                    "--manifest",
                    str(manifest),
                    "--progress",
                    str(progress),
                    "--dry-run",
                    "--limit",
                    "1",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            events = [
                json.loads(line)
                for line in (progress / "events.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertEqual(events[-1]["state"], "DONE")

    def test_cherry_pick_runner_records_attention_memory_when_enabled(self):
        script = SKILLS / "cherry-pick-runner" / "scripts" / "cherry_pick_runner.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            subprocess.run(["git", "init"], cwd=root, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "config", "user.email", "agent@example.com"], cwd=root, check=True)
            subprocess.run(["git", "config", "user.name", "Agent"], cwd=root, check=True)
            (root / "a.txt").write_text("base\n", encoding="utf-8")
            subprocess.run(["git", "add", "a.txt"], cwd=root, check=True)
            subprocess.run(["git", "commit", "-m", "base"], cwd=root, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "switch", "-c", "feature"], cwd=root, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            (root / "a.txt").write_text("feature\n", encoding="utf-8")
            subprocess.run(["git", "commit", "-am", "feature change"], cwd=root, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            sha = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=root,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            ).stdout.strip()
            subprocess.run(["git", "switch", "master"], cwd=root, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            manifest = root / "patches.jsonl"
            config = root / "runner-config.json"
            progress = root / "progress"
            memory = root / "memories"
            manifest.write_text(
                json.dumps({"seq": 1, "sha": sha, "title": "feature change", "risk": "low", "files": ["a.txt"]})
                + "\n",
                encoding="utf-8",
            )
            config.write_text(
                json.dumps(
                    {
                        "worker_count": 1,
                        "quick_build_commands": ["sh -c 'echo error: forced build failure; exit 1'"],
                        "quick_test_commands": [],
                        "build_repair": {"max_attempts": 0, "command": []},
                        "test_repair": {"max_attempts": 0, "command": []},
                        "memory": {"enabled": True, "memory_dir": str(memory), "record_attention": True},
                    }
                )
                + "\n",
                encoding="utf-8",
            )

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "run",
                    "--manifest",
                    str(manifest),
                    "--config",
                    str(config),
                    "--progress",
                    str(progress),
                    "--cwd",
                    str(root),
                    "--limit",
                    "1",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 1)
            rows = [
                json.loads(line)
                for line in (memory / "candidates.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertTrue(any(row["kind"] == "runner-attention" and row["sha"] == sha for row in rows))

    def test_metaxgpu_operator_marks_latest_attention_patch_done(self):
        script = SKILLS / "metaxgpu-cherry-pick-operator" / "scripts" / "complete_manual_patch.py"
        with tempfile.TemporaryDirectory() as tmp:
            progress = Path(tmp) / "progress"
            progress.mkdir()
            (progress / "events.jsonl").write_text(
                "\n".join(
                    [
                        '{"ts":"2026-05-07T12:00:00+08:00","agent":"runner-001","sha":"aaa111","seq":1,"title":"clean","state":"DONE","files":["llvm/lib/Target/MetaxGPU/A.cpp"],"message":"patch completed"}',
                        '{"ts":"2026-05-07T12:05:00+08:00","agent":"runner-001","sha":"bbb222","seq":2,"title":"conflict","state":"NEED_HUMAN","files":["llvm/lib/TargetParser/Triple.cpp"],"message":"resolve conflict then resume"}',
                    ]
                )
                + "\n",
                encoding="utf-8",
            )

            proc = subprocess.run(
                [sys.executable, str(script), "--progress", str(progress), "--agent", "claude-001"],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            events = [
                json.loads(line)
                for line in (progress / "events.jsonl").read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
            self.assertEqual(events[-1]["sha"], "bbb222")
            self.assertEqual(events[-1]["state"], "DONE")
            self.assertEqual(events[-1]["agent"], "claude-001")
            dashboard = (progress / "DASHBOARD.md").read_text(encoding="utf-8")
            self.assertIn("Done: 2", dashboard)
            self.assertIn("Need human: 0", dashboard)

    def test_metaxgpu_operator_uses_parent_output_layout(self):
        script = SKILLS / "metaxgpu-cherry-pick-operator" / "scripts" / "complete_manual_patch.py"
        help_proc = subprocess.run(
            [sys.executable, str(script), "--help"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        self.assertEqual(help_proc.returncode, 0, help_proc.stderr)
        self.assertIn("../output/progress-master", help_proc.stdout)

        operator_doc = (SKILLS / "metaxgpu-cherry-pick-operator" / "SKILL.md").read_text(encoding="utf-8")
        preflight_doc = (ROOT / "docs" / "claude-preflight.md").read_text(encoding="utf-8")
        for text in (operator_doc, preflight_doc):
            self.assertIn("../output/patches-master.jsonl", text)
            self.assertIn("../output/runner-config.json", text)
            self.assertIn("../output/progress-master", text)

    def test_agent_memory_records_promotes_and_searches_trusted_memory(self):
        script = SKILLS / "agent-memory" / "scripts" / "memory.py"
        with tempfile.TemporaryDirectory() as tmp:
            memory = Path(tmp) / "memories"

            record = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "record",
                    "--memory-dir",
                    str(memory),
                    "--kind",
                    "llvm-api-change",
                    "--summary",
                    "Use getIterator overload for moveBefore insertion points.",
                    "--source",
                    "llvm/include/llvm/IR/Instruction.h",
                    "--applies-to",
                    "LLVM22",
                    "--applies-to",
                    "MetaxGPU",
                    "--evidence",
                    "ninja check-llvm-codegen-metax passed",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(record.returncode, 0, record.stderr)
            candidate = json.loads(record.stdout)
            self.assertEqual(candidate["confidence"], "candidate")
            self.assertTrue((memory / "candidates.jsonl").is_file())

            promote = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "promote",
                    "--memory-dir",
                    str(memory),
                    "--id",
                    candidate["id"],
                    "--reviewer",
                    "human",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(promote.returncode, 0, promote.stderr)
            trusted = json.loads(promote.stdout)
            self.assertEqual(trusted["confidence"], "trusted")
            self.assertEqual(trusted["reviewer"], "human")

            search = subprocess.run(
                [sys.executable, str(script), "search", "--memory-dir", str(memory), "--query", "moveBefore"],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(search.returncode, 0, search.stderr)
            rows = json.loads(search.stdout)
            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0]["id"], candidate["id"])

    def test_agent_memory_summarizes_progress_events(self):
        script = SKILLS / "agent-memory" / "scripts" / "memory.py"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            memory = root / "memories"
            progress = root / "progress"
            progress.mkdir()
            (progress / "events.jsonl").write_text(
                "\n".join(
                    [
                        '{"ts":"2026-05-07T12:00:00+08:00","agent":"runner-001","sha":"aaa111","seq":1,"state":"DONE","message":"patch completed"}',
                        '{"ts":"2026-05-07T12:05:00+08:00","agent":"runner-001","sha":"bbb222","seq":2,"state":"NEED_HUMAN","message":"semantic conflict"}',
                        '{"ts":"2026-05-07T12:08:00+08:00","agent":"runner-001","sha":"bbb222","seq":2,"state":"DONE","message":"manual fix verified"}',
                    ]
                )
                + "\n",
                encoding="utf-8",
            )

            proc = subprocess.run(
                [
                    sys.executable,
                    str(script),
                    "summarize-session",
                    "--memory-dir",
                    str(memory),
                    "--progress",
                    str(progress),
                    "--session-id",
                    "pilot-20",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            summary = json.loads(proc.stdout)
            self.assertEqual(summary["session_id"], "pilot-20")
            self.assertEqual(summary["patch_count"], 2)
            self.assertEqual(summary["states"]["DONE"], 2)
            self.assertEqual(summary["states"]["NEED_HUMAN"], 1)
            self.assertTrue((memory / "session-summaries" / "pilot-20.json").is_file())


if __name__ == "__main__":
    unittest.main()
