#!/usr/bin/env python3
"""Classify LLVM lit/FileCheck failures for upgrade workflows."""

import argparse
from pathlib import Path
import shutil
import subprocess
import sys


def read(path):
    return Path(path).read_text(encoding="utf-8", errors="replace")


def has_autogen(text):
    return "Assertions have been autogenerated" in "\n".join(text.splitlines()[:8])


def run_lit(test, build, lit):
    exe = lit or shutil.which("llvm-lit") or shutil.which("lit")
    if not exe:
        return 2, "lit executable not found. Pass --lit or add llvm-lit/lit to PATH."
    cmd = [exe, "-vv", "--dump-input=always", test]
    env = None
    if build:
        bindir = str(Path(build) / "bin")
        env = dict(**__import__("os").environ)
        env["PATH"] = bindir + ":" + env.get("PATH", "")
    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=env)
    return proc.returncode, proc.stdout


def classify(test_text, log_text, test_path):
    lower = (log_text + "\n" + test_path).lower()
    autogen = has_autogen(test_text)
    if "timeout" in lower or "not found" in lower or "no such file" in lower:
        return "INFRA_OR_FLAKE"
    if "metax" in lower:
        return "DOWNSTREAM_BREAK"
    if "assertion" in lower or "llvm error" in lower or "crash" in lower or "verifier" in lower:
        return "SEMANTIC_REGRESSION"
    if autogen and ("filecheck" in lower or "check-" in lower or "expected string not found" in lower):
        return "PURE_TEXT_DRIFT"
    return "UNKNOWN_REVIEW_NEEDED"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("test")
    parser.add_argument("--llvm-build")
    parser.add_argument("--lit")
    parser.add_argument("--from-log")
    parser.add_argument("--save-log")
    args = parser.parse_args()

    test_text = read(args.test)
    if args.from_log:
        code = 1
        log_text = read(args.from_log)
    else:
        code, log_text = run_lit(args.test, args.llvm_build, args.lit)
    if args.save_log:
        Path(args.save_log).write_text(log_text, encoding="utf-8")

    result = classify(test_text, log_text, args.test)
    print(f"test: {args.test}")
    print(f"lit-exit-code: {code}")
    print(f"autogenerated-checks: {has_autogen(test_text)}")
    print(f"classification: {result}")
    if result == "PURE_TEXT_DRIFT":
        print("next: run update-test-checks in dry mode, then --apply if the diff is expected.")
    elif result in {"DOWNSTREAM_BREAK", "SEMANTIC_REGRESSION"}:
        print("next: inspect source changes and bisect/ground APIs before editing tests.")
    elif result == "INFRA_OR_FLAKE":
        print("next: fix runner environment before changing code.")
    return 0 if code == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())

