#!/usr/bin/env python3
"""Safely select and run LLVM update_*_test_checks.py scripts."""

import argparse
from pathlib import Path
import subprocess
import sys


def read_text(path):
    return Path(path).read_text(encoding="utf-8", errors="replace")


def has_autogen_header(text):
    first = "\n".join(text.splitlines()[:8])
    return "Assertions have been autogenerated" in first


def run_lines(text):
    return [line for line in text.splitlines() if "RUN:" in line]


def infer_kind(test, text, forced):
    if forced:
        return forced
    suffix = Path(test).suffix
    joined = "\n".join(run_lines(text))
    if suffix == ".mir":
        return "mir"
    if " llc " in f" {joined} " or "| llc" in joined or "llc" in joined:
        return "llc"
    if " opt " in f" {joined} " or "| opt" in joined or "opt" in joined:
        return "opt"
    return "unknown"


def script_and_args(kind, src, build):
    utils = src / "llvm" / "utils"
    bin_dir = build / "bin"
    if kind == "llc":
        return utils / "update_llc_test_checks.py", ["--llc-binary", str(bin_dir / "llc")]
    if kind == "opt":
        return utils / "update_test_checks.py", ["--opt-binary", str(bin_dir / "opt")]
    if kind == "mir":
        return utils / "update_mir_test_checks.py", ["--llc-binary", str(bin_dir / "llc")]
    return None, []


def git_diff(test):
    proc = subprocess.run(["git", "diff", "--", test], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return proc.stdout if proc.returncode == 0 else proc.stderr


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("test")
    parser.add_argument("--llvm-source", required=True)
    parser.add_argument("--llvm-build", required=True)
    parser.add_argument("--kind", choices=["llc", "opt", "mir"])
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    test = Path(args.test)
    text = read_text(test)
    autogen = has_autogen_header(text)
    kind = infer_kind(test, text, args.kind)
    script, extra = script_and_args(kind, Path(args.llvm_source), Path(args.llvm_build))

    print(f"test: {test}")
    print(f"autogenerated: {autogen}")
    print(f"inferred-kind: {kind}")
    if not autogen:
        print("refusing: no autogenerated CHECK header. Escalate for human review.")
        return 3
    if script is None or not script.exists():
        print("refusing: could not find a supported update script.")
        return 2

    cmd = [sys.executable, str(script)] + extra + [str(test)]
    print("command:", " ".join(cmd))
    if not args.apply:
        print("dry-run: add --apply to run the command.")
        return 0

    proc = subprocess.run(cmd, text=True)
    if proc.returncode != 0:
        return proc.returncode
    print("\n# Diff\n")
    print(git_diff(str(test)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

